### ISSUE TITLE
The attribute is not allowed.

### ISSUE THREAD

**Issue by shinesoftware** [mage2pro/sales-sequence#1]
Hello guys,

I have found an issue when I have installed your module:

> Element 'field', attribute 'dfMax': The attribute 'dfMax' is not allowed.

There is another error in this element:

> <dfExtension>Dfe_SalesSequence</dfExtension>

thanks

**Comment by dmitrii-fediuk** [comment]
I support the paying customers only.
The module can be bought here: https://mage2.pro/t/512
