### ISSUE TITLE
«Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126» in Magento 2.4

### ISSUE THREAD

**Issue by mtjweb** [mage2pro/sales-sequence#2]
I tried to install it on Magento 2.4, but got the following error when executing bin/magento setup:upgrade

SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs

**Comment by dmitrii-fediuk** [comment]
You can hire me in Upwork to solve your problem: [upwork.com/fl/mage2pro](https://www.upwork.com/fl/mage2pro)

**Comment by mtjweb** [comment]
Thank you, but it is just a bug report.

**Comment by mtjweb** [comment]
Problem was solved by adding the following code to my.cnf and restarting MySQL-server:

```
[mysqld]
innodb_log_file_size=512M
innodb_strict_mode=0
```
